// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAayO61P3gmMV1bHgz4Mow-Dvev7xGcVKg',
    appId: '1:210125838789:web:d86819bb5823ca8b58d3ac',
    messagingSenderId: '210125838789',
    projectId: 'testingcli-634ef',
    authDomain: 'testingcli-634ef.firebaseapp.com',
    storageBucket: 'testingcli-634ef.appspot.com',
    measurementId: 'G-89BVMJBXTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmBrlp_OU3t0IzMdN9vIcP2U9UnGsbuU',
    appId: '1:210125838789:android:6be7caa7f729a1b658d3ac',
    messagingSenderId: '210125838789',
    projectId: 'testingcli-634ef',
    storageBucket: 'testingcli-634ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmzP61RAJhwSmG26PmgeQATV1NZ7yyp4',
    appId: '1:210125838789:ios:e726b96fd2a4884f58d3ac',
    messagingSenderId: '210125838789',
    projectId: 'testingcli-634ef',
    storageBucket: 'testingcli-634ef.appspot.com',
    iosBundleId: 'com.example.frontendWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlmzP61RAJhwSmG26PmgeQATV1NZ7yyp4',
    appId: '1:210125838789:ios:e726b96fd2a4884f58d3ac',
    messagingSenderId: '210125838789',
    projectId: 'testingcli-634ef',
    storageBucket: 'testingcli-634ef.appspot.com',
    iosBundleId: 'com.example.frontendWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAayO61P3gmMV1bHgz4Mow-Dvev7xGcVKg',
    appId: '1:210125838789:web:e825f0c7b836d70758d3ac',
    messagingSenderId: '210125838789',
    projectId: 'testingcli-634ef',
    authDomain: 'testingcli-634ef.firebaseapp.com',
    storageBucket: 'testingcli-634ef.appspot.com',
    measurementId: 'G-BVEJYYV17E',
  );
}
